<?php

namespace Knappster\CapitaPay360\SoapClient\Capita;

use Knappster\CapitaPay360\SoapClient\Capita\Types as Type;
use Soap\Encoding\ClassMap\ClassMapCollection;
use Soap\Encoding\ClassMap\ClassMap;

class CapitaClassmap
{
    public static function types() : \Soap\Encoding\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection(
            new ClassMap('https://support.capita-software.co.uk/selfservice/?commonFoundation', 'credentials', Type\Credentials::class),
            new ClassMap('https://support.capita-software.co.uk/selfservice/?commonFoundation', 'subject', Type\Subject::class),
            new ClassMap('https://support.capita-software.co.uk/selfservice/?commonFoundation', 'requestIdentification', Type\RequestIdentification::class),
            new ClassMap('https://support.capita-software.co.uk/selfservice/?commonFoundation', 'signature', Type\Signature::class),
            new ClassMap('http://www.capita-software-services.com/scp/simple', 'scpSimpleInvokeRequest', Type\ScpSimpleInvokeRequest::class),
            new ClassMap('http://www.capita-software-services.com/scp/simple', 'simpleSale', Type\SimpleSale::class),
            new ClassMap('http://www.capita-software-services.com/scp/simple', 'items', Type\Items::class),
            new ClassMap('http://www.capita-software-services.com/scp/simple', 'surchargeable', Type\Surchargeable::class),
            new ClassMap('http://www.capita-software-services.com/scp/simple', 'applyScpConfig', Type\ApplyScpConfig::class),
            new ClassMap('http://www.capita-software-services.com/scp/simple', 'simpleItem', Type\SimpleItem::class),
            new ClassMap('http://www.capita-software-services.com/scp/simple', 'scpSimpleQueryResponse', Type\ScpSimpleQueryResponse::class),
            new ClassMap('http://www.capita-software-services.com/scp/simple', 'simplePaymentResult', Type\SimplePaymentResult::class),
            new ClassMap('http://www.capita-software-services.com/scp/simple', 'simplePayment', Type\SimplePayment::class),
            new ClassMap('http://www.capita-software-services.com/scp/simple', 'simpleSaleSummary', Type\SimpleSaleSummary::class),
            new ClassMap('http://www.capita-software-services.com/scp/simple', 'items', Type\Items::class),
            new ClassMap('http://www.capita-software-services.com/scp/simple', 'simpleItemSummary', Type\SimpleItemSummary::class),
            new ClassMap('http://www.capita-software-services.com/scp/simple', 'scpSimpleInvokeResponse', Type\ScpSimpleInvokeResponse::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'invokeResult', Type\InvokeResult::class),
            new ClassMap('http://www.capita-software-services.com/scp/simple', 'scpSimpleQueryRequest', Type\ScpSimpleQueryRequest::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'requestWithCredentials', Type\RequestWithCredentials::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'scpVersionRequest', Type\ScpVersionRequest::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'scpVersionResponse', Type\ScpVersionResponse::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'scpInvokeRequest', Type\ScpInvokeRequest::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'routing', Type\Routing::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'additionalInstructions', Type\AdditionalInstructions::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'walletRequest', Type\WalletRequest::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'paymentMethods', Type\PaymentMethods::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'paymentMethodType', Type\PaymentMethodType::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'parameters', Type\Parameters::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'parameter', Type\Parameter::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'recurringPayments', Type\RecurringPayments::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'acceptedCards', Type\AcceptedCards::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'acceptedCardList', Type\AcceptedCardList::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'stageIndicator', Type\StageIndicator::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'billingDetails', Type\BillingDetails::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'card', Type\Card::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'cardDetails', Type\CardDetails::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'storedCardKey', Type\StoredCardKey::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'cardHolderDetails', Type\CardHolderDetails::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'address', Type\Address::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'contact', Type\Contact::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'saleBase', Type\SaleBase::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'summaryData', Type\SummaryData::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'contactDetails', Type\ContactDetails::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'threePartName', Type\ThreePartName::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'nonPaymentData', Type\NonPaymentData::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'mcc6012', Type\Mcc6012::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'lgSaleDetails', Type\LgSaleDetails::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'postageAndPacking', Type\PostageAndPacking::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'taxItem', Type\TaxItem::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'vatItem', Type\VatItem::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'vatBase', Type\VatBase::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'lgPnpDetails', Type\LgPnpDetails::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'surchargeItemDetails', Type\SurchargeItemDetails::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'surchargeInfo', Type\SurchargeInfo::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'cardSurchargeRate', Type\CardSurchargeRate::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'acceptedCardType', Type\AcceptedCardType::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'surchargeBasis', Type\SurchargeBasis::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'taxSurcharge', Type\TaxSurcharge::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'vatSurcharge', Type\VatSurcharge::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'itemBase', Type\ItemBase::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'notificationEmails', Type\NotificationEmails::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'lgItemDetails', Type\LgItemDetails::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'customerInfo', Type\CustomerInfo::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'bankDetails', Type\BankDetails::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'bacsBankAccount', Type\BacsBankAccount::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'scpInvokeResponse', Type\ScpInvokeResponse::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'invokeResult', Type\InvokeResult::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'scpResponse', Type\ScpResponse::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'errorDetails', Type\ErrorDetails::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'scpQueryRequest', Type\ScpQueryRequest::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'scpQueryResponse', Type\ScpQueryResponse::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'storeCardResult', Type\StoreCardResult::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'storedCardDetails', Type\StoredCardDetails::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'emailResult', Type\EmailResult::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'paymentResultBase', Type\PaymentResultBase::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'paymentBase', Type\PaymentBase::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'paymentHeader', Type\PaymentHeader::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'paymentMethod', Type\PaymentMethod::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'authDetails', Type\AuthDetails::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'authDccInfo', Type\AuthDccInfo::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'displayAmountInfo', Type\DisplayAmountInfo::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'nonCardPayment', Type\NonCardPayment::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'openBankingPayment', Type\OpenBankingPayment::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'multiAuthorisationStatusDetails', Type\MultiAuthorisationStatusDetails::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'itemSummaryBase', Type\ItemSummaryBase::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'surchargeDetails', Type\SurchargeDetails::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'securityDetails', Type\SecurityDetails::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'threeDSecure', Type\ThreeDSecure::class),
        );
    }

    public static function enums() : \Soap\Encoding\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection(
            new ClassMap('http://www.capita-software-services.com/portal-api', 'systemCode', Type\SystemCode::class),
            new ClassMap('http://www.capita-software-services.com/portal-api', 'systemCodeDirect', Type\SystemCodeDirect::class),
            new ClassMap('http://www.capita-software-services.com/portal-api', 'recordSource', Type\RecordSource::class),
            new ClassMap('http://www.capita-software-services.com/portal-api', 'keySwipe', Type\KeySwipe::class),
            new ClassMap('http://www.capita-software-services.com/portal-api', 'cardType', Type\CardType::class),
            new ClassMap('http://www.capita-software-services.com/portal-api', 'cardTranType', Type\CardTranType::class),
            new ClassMap('http://www.capita-software-services.com/portal-api', 'eCommerceTerminalType', Type\ECommerceTerminalType::class),
            new ClassMap('http://www.capita-software-services.com/portal-api', 'securityAttempted', Type\SecurityAttempted::class),
            new ClassMap('http://www.capita-software-services.com/portal-api', 'securityResult', Type\SecurityResult::class),
            new ClassMap('http://www.capita-software-services.com/portal-api', 'surchargeType', Type\SurchargeType::class),
            new ClassMap('http://www.capita-software-services.com/portal-api', 'cardDescription', Type\CardDescription::class),
            new ClassMap('http://www.capita-software-services.com/portal-api', 'panEntryMethod', Type\PanEntryMethod::class),
            new ClassMap('http://www.capita-software-services.com/portal-api', 'portalAction', Type\PortalAction::class),
            new ClassMap('https://support.capita-software.co.uk/selfservice/?commonFoundation', 'algorithm', Type\Algorithm::class),
            new ClassMap('https://support.capita-software.co.uk/selfservice/?commonFoundation', 'subjectType', Type\SubjectType::class),
            new ClassMap('https://support.capita-software.co.uk/selfservice/?commonFoundation', 'systemCode', Type\SystemCode::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'requestType', Type\RequestType::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'scpSpecialUrl', Type\ScpSpecialUrl::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'paymentAuthorityType', Type\PaymentAuthorityType::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'responseInterface', Type\ResponseInterface::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'cardType', Type\CardType::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'transactionState', Type\TransactionState::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'status', Type\Status::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'responseVersion', Type\ResponseVersion::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'transactionStatus', Type\TransactionStatus::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'cardCategory', Type\CardCategory::class),
            new ClassMap('http://www.capita-software-services.com/scp/base', 'prepaidIndicator', Type\PrepaidIndicator::class),
        );
    }
}

